### ISSUE TITLE
WARNING: DO NOT USE THIS PROJECT

### ISSUE THREAD

**Issue by Crazypersonalph** [Nulkem/betterseqta#23]
As most of you will know, this project has not been very active over the past few months

It seems as though Nulkem has abandoned this project

I would like to issue a warning for you to stop using this version of BetterSeqta, and transition over to here: https://github.com/crazypersonalph/betterseqta/

There are some major security vulnerabilities in this current version of the project

In the fork, these vulnerabilities have been fixed

Thank you

**Comment by Nulkem** [comment]
This is not as big of the deal as you are making it out to be. The only potential risk introduced by the `stringtoHTML` function is the user created shortcuts input which is stored and used locally, so any malicious user input parsed in the function would only affect themselves.

**Comment by Crazypersonalph** [comment]
> This is not as big of the deal as you are making it out to be. The only potential risk introduced by the `stringtoHTML` function is the user created shortcuts input which is stored and used locally, so any malicious user input parsed in the function would only affect themselves.

But why isn't it being fixed anyway? The fix is pretty easy, just sanitize the input.

**Comment by Nulkem** [comment]
Generally, I am not making any new changes to this extension since I am unable to test them. If any major security vulnerabilities are found in the future, I’ll look into them.

**Comment by Crazypersonalph** [comment]
> Generally, I am not making any new changes to this extension since I am unable to test them. If any major security vulnerabilities are found in the future, I’ll look into them.

What is happening with the ownership of the plugin?

I'm currently patching a lot of issues in my fork, are you willing to transfer ownership of the plugin?

I do a lot of cybersecurity stuff, I might be able to catch security issues before they enter into production code

**Comment by AustinAggiss** [comment]
I figured you had been unable to test, since I assume you've left your school and therefore have no more access to SEQTA to test on. I feel that transferring ownership of this repository (or allowing modifications without approval by contributors such as @Crazypersonalph) would be good to continue improvements.

Most of my school already use it now and many 1000s of other students also. This means that publishing to the Chrome Web Store is also very important (and Firefox Add-Ons). Remember that people are generally pretty lazy and won't go out of their way to update to a new version of an extension, when the browser does it for them already. I haven't published an extension myself and I am unfamiliar with the processes involved with updates, ownership etc.

My final point being that if this won't be something you update often yourself, I feel that other contributors would be able to maintain the project continuously.
