### ISSUE TITLE
Better Seqta For safari?

### ISSUE THREAD

**Issue by wackiiy** [Nulkem/betterseqta#3]
Title says all. I think apple charges 99 dollars a year though for a developer subscription

**Comment by Nulkem** [comment]
Currently, there are no plans for a Safari version of BetterSEQTA, mostly due to the funding required to publish it as you mentioned.

However, there may be a chance for an unsigned version of the extension for Safari, but this inherently has a few issues. After some testing, I discovered a few issues which would require rewriting some parts specifically for a Safari version, which is time consuming but still possible. 

Additionally, Safari requires the user to enable the setting 'Allow Unsigned Extensions' with a password every time Safari is reopened after quitting for the extension to work.

If this is something that people are willing to deal with, I might work on an 'unofficial' version for Safari that would be available on the releases tab on GitHub, as well as instructions on how to use it.
